VERSION="2.0.0"

# 발행자 계정 정보
ACCOUNTS=[
  "GCPKRYYXAOMTIQUA2B7AGCJWFFPAW3IJ34E3XPK4HQCDMJFA5FLKM7ZL"
]

# PIROCKET 토큰 정보
[[CURRENCIES]]
code = "PIROCKET"
issuer = "GCPKRYYXAOMTIQUA2B7AGCJWFFPAW3IJ34E3XPK4HQCDMJFA5FLKM7ZL"
display_decimals = 7
name = "PiRocket"
desc = "PiRocket - Stellar Mainnet 밈코인"
image = "https://successclub.github.io/pirocket/pirocket-logo.png"


